name = "3d-conversion-api"
compatibility_date = "2023-10-01"

[env.production]
workers_dev = false

[vars]
API_VERSION = "1.0.0"
MAX_FILE_SIZE = "104857600"

[env.production.d1_databases]
binding = "DB"
database_name = "3d-conversion-db"

[env.production.r2_buckets]
binding = "FILE_BUCKET"
bucket_name = "3d-conversion-files"

[env.production.queues]
binding = "CONVERSION_QUEUE"
queue_name = "conversion-queue"
