name = "3d-conversion-api"
compatibility_date = "2023-10-01"

[vars]
API_VERSION = "1.0.0"
MAX_FILE_SIZE = "100MB"

[env.production.d1_databases]
binding = "DB"
database_name = "3d-conversion-db"

[env.production.r2_buckets]
binding = "FILE_BUCKET"
bucket_name = "3d-conversion-files"
