name = "3d-conversion-api"
compatibility_date = "2023-10-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
workers_dev = true  # اول روی workers.dev تست می‌کنیم

[vars]
API_VERSION = "1.0.0"
MAX_FILE_SIZE = "104857600"
CONVERSION_TIMEOUT = "300"
SERVICE_NAME = "3D Conversion API"

[env.production.vars]
NODE_ENV = "production"
LOG_LEVEL = "info"
