name = "3d-conversion-app"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
account_id = "YOUR_ACCOUNT_ID"
zone_id = "YOUR_ZONE_ID"
routes = [
    "3d-conversion.tetrashop.workers.dev/*",
    "tetrashop.com/*"
]

[[env.production.vars]]
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "password"
DB_NAME = "conversion_3d"
