export async function onRequestGet(context) {
  try {
    const { model_id } = context.params;
    
    // شبیه‌سازی فایل 3D
    const modelContent = `# Model ${model_id}
# Generated by 3D Conversion App
v 0.0 0.0 0.0
v 1.0 0.0 0.0
v 1.0 1.0 0.0
f 1 2 3`;
    
    return new Response(modelContent, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="model-${model_id}.obj"`
      }
    });
  } catch (error) {
    return new Response(JSON.stringify({
      error: "Model not found"
    }), { status: 404 });
  }
}
