export async function onRequestGet(context) {
  try {
    const { modelId } = context.params;
    const modelContent = `# 3D Model: ${modelId}\n# Generated by 3D Conversion App\n`;
    
    return new Response(modelContent, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="model-${modelId}.obj"`,
        'Access-Control-Allow-Origin': '*'
      }
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: "Model not found" }), { status: 404 });
  }
}
